langues = [
    "Francais",
    "Anglais",
    # "Fulfulde",
    # "Bulu",
    "Gbaya",
    # "MASSANA",
    # "Guiziga",
    # "Kapsiki",
    # "Tupurri",
    # "Bafia",
    # "Ejagham",
    # "Ghomala",
    # "Ewondo",
    # "Ngiemboon",
    # "Dii",
    # "Vute",
    # "Limbum",
    # "Mofa",
    # "Mofu_Gudur",
    # "Doyayo",
    # "Guidar",
    # "Peere_Nt&Psalms",
    # "Samba_Leko",
    # "Du_na_sdik_na_wiini_Alaw"
    ]
